//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Entity;
using System.Collections.Generic;
using UnityEngine;


namespace Database
{
	public class MyMonsterTable
	{
		private SqliteDatabase sqlDB;
		public MyMonsterTable ()
		{
			sqlDB = new SqliteDatabase("farm.db");
		}

		/**
		 * MyMonsterをデフォルト0才で登録する。
		 * @param name モンスター名
		 * @param type モンスタータイプ
		 * 
		 */
		public void registMyMonster(string dispName, string name, int type) {
			string query = "insert into MyMonster(dispname, name, old, type) values('" + dispName + "','" + name + "', 0," + type + ")";
			sqlDB.ExecuteNonQuery(query);
		}

		/**
		 * idをもとに自分の今使用しているモンスター情報を取得する
		 */
		public Entity.MyMonster selectMyMoster(int id) {
			// Select
			string selectQuery = "select * from MyMonster where type = " + id;
			DataTable dataTable = sqlDB.ExecuteQuery(selectQuery);
			Entity.MyMonster entity = null;
			foreach(DataRow dr in dataTable.Rows){
				entity = new Entity.MyMonster((int)dr["id"], (string)dr["name"], (string)dr["dispname"], (int)dr["old"], (int)dr["type"]);
			}
			Debug.Log (entity.getDispname());
			return entity;
		}
		/**
		 * 手持ちのMonster一覧情報を取得する
		 */
		public List<Entity.MyMonster> selectMyMosters() {
			// Select
			string selectQuery = "select m1.id as id, m1.dispName  as dispname, m1.name as name, m1.old as old, m1.type as type from MyMonster m1 left join Monsters m2 ON m1.type = m2.type where m1.type = m2.type;";
			DataTable dataTable = sqlDB.ExecuteQuery(selectQuery);
			var entities = new List<Entity.MyMonster>();
			foreach(DataRow dr in dataTable.Rows){
				Entity.MyMonster entity = new Entity.MyMonster((int)dr["id"], (string)dr["name"], (string)dr["dispname"], (int)dr["old"], (int)dr["type"]);
				entities.Add(entity);
			}
			return entities;
		}

		public Entity.MyMonster selectMyMonsterIdentificationName (string dispName)
		{
			string selectQuery = "select * from MyMonster where dispname = \"" + dispName + "\"";
			DataTable dataTable = sqlDB.ExecuteQuery(selectQuery);
			Entity.MyMonster entity = null;
			foreach(DataRow dr in dataTable.Rows){
				entity = new Entity.MyMonster((int)dr["id"], (string)dr["name"], (string)dr["dispname"], (int)dr["old"], (int)dr["type"]);
			}
			return entity;
		}

		/**
		 * 全件削除
		 */
		public void deleteAll() {

			string deleteQuery = "delete from MyMonster";
			sqlDB.ExecuteNonQuery(deleteQuery);
		}

		/**
		 * ニックネームをもとにentityを1件取得する
		 */
		public Entity.MyMonster selectMyMosterByNickName (string dispName)
		{
			// Select
			string selectQuery = "select * from MyMonster where dispname = '" + dispName + "'";
			DataTable dataTable = sqlDB.ExecuteQuery(selectQuery);
			Entity.MyMonster entity = null;
			if (dataTable.Rows != null) {
				foreach(DataRow dr in dataTable.Rows){
					entity = new Entity.MyMonster((int)dr["id"], (string)dr["name"], (string)dr["dispname"], (int)dr["old"], (int)dr["type"]);
				}
			}
			return entity;
		}

		public Entity.MyMonster selectMyMosterByType(string type)
		{
			// Select
			string selectQuery = "select * from MyMonster where type = '" + type + "'";
			DataTable dataTable = sqlDB.ExecuteQuery(selectQuery);
			Entity.MyMonster entity = null;
			if (dataTable.Rows != null) {
				foreach(DataRow dr in dataTable.Rows){
					entity = new Entity.MyMonster((int)dr["id"], (string)dr["name"], (string)dr["dispname"], (int)dr["old"], (int)dr["type"]);
				}
			}
			return entity;
		}
	}
}

