//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Entity;
using System.Collections.Generic;


namespace Database
{
	public class MyMonsterTable
	{
		private SqliteDatabase sqlDB;
		public MyMonsterTable ()
		{
			sqlDB = new SqliteDatabase("farm.db");
		}

		/**
		 * MyMonsterをデフォルト0才で登録する。
		 * @param name モンスター名
		 * @param type モンスタータイプ
		 * 
		 */
		public void registMyMonster(string name, int type) {
			string query = "insert into MyMonster values(" + name + ", 0," + type + ")";
			sqlDB.ExecuteNonQuery(query);
		}

		/**
		 * typeをもとに自分の今使用しているモンスター情報を取得する
		 * typeにかんしては、Const.Constを参照
		 */
		public Entity.MyMonster selectMyMoster(int type) {
			// Select
			string selectQuery = "select * from MyMonster where type = " + type;
			DataTable dataTable = sqlDB.ExecuteQuery(selectQuery);
			Entity.MyMonster entity = null;
			foreach(DataRow dr in dataTable.Rows){
				entity = new Entity.MyMonster((int)dr["id"], (string)dr["name"], (string)dr["dispname"], (int)dr["old"], (int)dr["type"]);
			}
			return entity;
		}
		/**
		 * 手持ちのMonster一覧情報を取得する
		 */
		public List<Entity.MyMonster> selectMyMosters() {
			// Select
			string selectQuery = "select * from MyMonster";
			DataTable dataTable = sqlDB.ExecuteQuery(selectQuery);
			var entities = new List<Entity.MyMonster>();
			foreach(DataRow dr in dataTable.Rows){
				Entity.MyMonster entity = new Entity.MyMonster((int)dr["id"], (string)dr["name"], (string)dr["dispname"], (int)dr["old"], (int)dr["type"]);
				entities.Add(entity);
			}
			return entities;
		}

		public Entity.MyMonster selectMyMonsterIdentificationName (string dispName)
		{
			string selectQuery = "select * from MyMonster where dispname = \"" + dispName + "\"";
			DataTable dataTable = sqlDB.ExecuteQuery(selectQuery);
			Entity.MyMonster entity = null;
			foreach(DataRow dr in dataTable.Rows){
				entity = new Entity.MyMonster((int)dr["id"], (string)dr["name"], (string)dr["dispname"], (int)dr["old"], (int)dr["type"]);
			}
			return entity;
		}
	}
}

