//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Entity;
using System.Collections.Generic;


namespace Database
{
	public class StatusTable
	{
		private SqliteDatabase sqlDB;
		public StatusTable ()
		{
			sqlDB = new SqliteDatabase("farm.db");
		}

		/**
		 * idをもとに自分の今使用しているモンスターステータスを取得する
		 */
		public Entity.Status selectStatusByID(int id) {
			// Select
			string selectQuery = "select * from Status where type = " + id;
			DataTable dataTable = sqlDB.ExecuteQuery(selectQuery);
			Entity.Status entity = null;
			foreach(DataRow dr in dataTable.Rows){
				entity = new Entity.Status((int)dr["type"], (int)dr["life"], (int)dr["power"], (int)dr["wise"], (int)dr["hit"], (int)dr["avoid"], (int)dr["deffence"]);
			}
			return entity;
		}
	}
}

