//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Entity
{
	public class Monsters
	{
		// auto increment
		private int id;
		// 識別名
		private string name;
		// 表示名
		private string dispname;
		// 説明文
		private string description;
		// 持っているかどうか(もってる=1, 持ってない = 0)
		private int isMine;
		public Monsters (int id, string name, string dispname, string description, int isMine)
		{
			this.id = id;
			this.name = name;
			this.dispname = dispname;
			this.description = description;
			this.isMine = isMine;
		}
		public int getId() {
			return this.id;
		}
		public string getName() {
			return this.name;
		}
		public string getDispname() {
			return this.dispname;
		}
		public string getDescription() {
			return this.description;
		}
		public int getIsMine(){
			return this.isMine;
		}
	}
}

