//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Entity
{
	public class MyMonster
	{
		// auto increment
		private int id;
		// 「daruman」のような不変固定の文字列。Const.Const参照
		private string name;
		private string dispname;
		// 年齢 1 - 50まで
		private int old;
		// Monsterテーブルで管理されるtypeと外部関連
		private int type;
		public MyMonster (int id, string name, string dispname, int old, int type)
		{
			this.id = id;
			this.name = name;
			this.dispname = dispname;
			this.old = old;
			this.type = type;
		}
		public int getId() {
			return this.id;
		}
		public string getName() {
			return this.name;
		}
		public string getDispname() {
			return this.dispname;
		}
		public int getOld() {
			return this.old;
		}
		public int getType(){
			return this.type;
		}
	}
}

