//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Entity
{
	public class Status
	{
		private int type;
		private int life;
		private int power;
		private int wise;
		private int hit;
		private int avoid;
		private int deffence;

		public Status (int type, int life, int power, int wise, int hit, int avoid, int deffence)
		{
			this.type = type;
			this.life = life;
			this.power = power;
			this.wise = wise;
			this.hit = hit;
			this.avoid = avoid;
			this.deffence = deffence;
		}
		public int getType() {
			return this.type;
		}
		public int getLife() {
			return this.life;
		}
		public int getPower() {
			return this.power;
		}
		public int getWise(){
			return this.wise;
		}
		public int getHit(){
			return this.hit;
		}
		public int getAvoid(){
			return this.avoid;
		}
		public int getDeffence(){
			return this.deffence;
		}
	}
}

