//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Const
{
	public class Const
	{
		public static readonly Dictionary<string, string> charactors = new Dictionary<string, string>();
		public static readonly Dictionary<string, string> charactorNames = new Dictionary<string, string>();
		public static readonly Dictionary<string, int> monsterTypes = new Dictionary<string, int>();
		public static readonly string nowMyMonsterID = "mymonster_id";
		public static readonly string birthMonsterID = "birth_monster_id"; // UnityAdd.csで使用


		static Const() {
			// prefabs
			charactors.Add ("daruman", "prefabs/daruman");
			charactors.Add ("antrope", "prefabs/antrope");
			charactors.Add ("aodanuki", "prefabs/aodanuki");
			charactors.Add ("crayslug", "prefabs/crayslug");
			charactors.Add ("goalem", "prefabs/goalem");
			charactors.Add ("kaoari", "prefabs/kaoari");
			charactors.Add ("goast", "prefabs/goast");
			charactors.Add ("alex", "prefabs/alex");

			// 日本語 <-> 識別子
			charactorNames.Add ("だるまん", "daruman");
			charactorNames.Add ("アントロープ", "antrope");
			charactorNames.Add ("あおだぬき", "aodanuki");
			charactorNames.Add ("スラッグ", "crayslug");
			charactorNames.Add ("ゴーレム", "goalem");
			charactorNames.Add ("かおあり", "kaoari");
			charactorNames.Add ("ごーすと", "goast");

			// types
			monsterTypes.Add ("daruman", 1);
			monsterTypes.Add ("aodanuki", 2);
			monsterTypes.Add ("antrope", 3);
			monsterTypes.Add ("crayslug", 4);
			monsterTypes.Add ("goalem", 5);
			monsterTypes.Add ("kaoari", 6);
			monsterTypes.Add ("goast", 7);
			monsterTypes.Add ("alex", 8);
		}
	}
}